---
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
matrix:
  include:
  - language: ruby
    rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes LIBRARIAN_VERBOSE=true
    script: "bundle exec rake lint && bundle exec rake librarian_spec SPEC_OPTS='--format documentation'"
  - language: ruby
    rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES=yes LIBRARIAN_VERBOSE=true
    script: "bundle exec rake lint && bundle exec rake librarian_spec SPEC_OPTS='--format documentation'"
  - language: ruby
    rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 6.0" STRICT_VARIABLES=yes LIBRARIAN_VERBOSE=true
    script: "bundle exec rake lint && bundle exec rake librarian_spec SPEC_OPTS='--format documentation'"
  - language: python
    python: 2.7
    script: "pip install yamllint && yamllint -c yamllint.yml spec/fixtures/hiera* spec/acceptance/nodesets/default.yml *.yml"
notifications:
  email:
    recipients:
      - 'alexharv074@gmail.com'
    on_success: never
    on_failure: always
