class profile::elasticsearch::data_node (

  # Mandatory params.
  Stdlib::Absolutepath     $datadir,
  Hash[String, Hash]       $firewall_multis,

  # Volume groups.
  Hash[String, Struct[{
    physical_volumes => Array[String],
    logical_volumes  => Hash[String, Struct[{
      mountpath      => Stdlib::Absolutepath
    }]]
  }]]                      $volume_groups,

  # Optional params.
  Hash                     $config                  = {},
  Hash                     $es_plugins              = {},
  Array[Pattern[/^-/]]     $jvm_options             = [],
  Integer[0,1]             $vm_swappiness           = undef,
  Integer                  $vm_max_map_count        = undef,
  Hash                     $ilm_policies            = {},

  # ES templates.
  Hash[String, Struct[{
    source => Pattern[/puppet:\/\/\//]
  }]]                      $es_templates            = {},

) {

  # Users of this profile should always allow this class to configure ES as a
  # data node.
  #
  if 'node.roles' in $config {
    fail("Do not specify node.roles in ${module_name}")
  }

  unless length($volume_groups) == 1 {
    fail('You must specify one volume group for the data dir')
  }

  # Note that the user must provide the custom fact espv pointing to the
  # physical volume for the data node filesystem.
  #
  assert_type(Stdlib::Absolutepath, $facts['espv'])

  create_resources(firewall_multi, $firewall_multis)
  create_resources(lvm::volume_group, $volume_groups)

  include profile::elasticsearch

  class { 'elasticsearch':
    config      => stdlib::merge($config, {'node.roles' => ['master', 'data', 'ingest']}),
    datadir     => $datadir,
    jvm_options => $jvm_options,
  }

  Mount[$datadir] -> File[$datadir]

  $remove_autoconfig_keystore_script = [
    '#!/bin/sh',
    'set -eu',
    '',
    'export ES_PATH_CONF=/etc/elasticsearch',
    'keystore=/usr/share/elasticsearch/bin/elasticsearch-keystore',
    'settings="',
    'xpack.security.http.ssl.keystore.secure_password',
    'xpack.security.transport.ssl.keystore.secure_password',
    'xpack.security.transport.ssl.truststore.secure_password',
    '"',
    '',
    'if [ "${1:-}" = "--check" ]; then',
    '  for setting in ${settings}; do',
    '    if "${keystore}" list | grep -Fxq "${setting}"; then',
    '      exit 0',
    '    fi',
    '  done',
    '  exit 1',
    'fi',
    '',
    'for setting in ${settings}; do',
    '  if "${keystore}" list | grep -Fxq "${setting}"; then',
    '    "${keystore}" remove "${setting}"',
    '  fi',
    'done',
    '',
  ].join("\n")

  file { '/usr/local/sbin/elk-remove-elasticsearch-autoconfig-keystore':
    ensure  => file,
    mode    => '0755',
    content => $remove_autoconfig_keystore_script,
    require => Class['elasticsearch::package'],
  }

  exec { 'remove autogenerated elasticsearch ssl keystore entries':
    command => '/usr/local/sbin/elk-remove-elasticsearch-autoconfig-keystore',
    onlyif  => '/usr/local/sbin/elk-remove-elasticsearch-autoconfig-keystore --check',
    require => File['/usr/local/sbin/elk-remove-elasticsearch-autoconfig-keystore'],
    before  => Service['elasticsearch'],
  }

  create_resources(elasticsearch::template, $es_templates)
  create_resources(elasticsearch::plugin, $es_plugins)
  create_resources(elasticsearch::ilm_policy, $ilm_policies)

  Sysctl {
    before => Service['elasticsearch']
  }

  if $vm_swappiness {
    sysctl { 'vm.swappiness': value => $vm_swappiness }
  }

  if $vm_max_map_count {
    sysctl { 'vm.max_map_count': value => $vm_max_map_count }
  }
}
