forge 'https://forgeapi.puppetlabs.com'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/ntp'
mod 'puppetlabs/lvm'
mod 'puppetlabs/firewall'
mod 'alexharvey/firewall_multi'
mod 'alexharvey/disable_transparent_hugepage'
mod 'pcfens/filebeat'

# Until my PRs to fix Issues #947 and #949 are merged.
#
mod 'elastic/elasticsearch',
  :git => 'https://github.com/alexharv074/puppet-elasticsearch.git',
  :branch => 'alex_master'

mod 'elastic/logstash'
mod 'arioch/redis'
mod 'elastic/kibana'
mod 'puppet/nginx'
mod 'camptocamp/archive'
mod 'thias/sysctl'
mod 'heini/wait_for'

# Dependencies.
#
# Although librarian-puppet can resolve the dependencies itself, g10k can't.
# The commented-out entries are specified in metadata.json by the parent
# module, but we don't actually need them.

# Dependencies of arioch/redis.
mod 'herculesteam/augeasproviders_core'
mod 'herculesteam/augeasproviders_sysctl'
#mod 'puppetlabs/apt'
mod 'stahnma/epel'

# Dependencies of all the elastic modules
#mod 'elastic/elastic_stack'

# Dependencies of elastic/elastic_stack
#mod 'puppet/yum'

# Dependencies of elastic/elasticsearch
mod 'richardc/datacat'

# Dependencies of pcfens/filebeat
#mod 'puppetlabs/powershell'

# Dependencies of puppet/nginx
mod 'puppetlabs/concat'
