forge 'https://forgeapi.puppetlabs.com'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/haproxy'
mod 'puppetlabs/ntp'
mod 'puppetlabs/lvm'
mod 'puppetlabs/firewall'
mod 'alexharvey/firewall_multi'
mod 'alexharvey/disable_transparent_hugepage'
mod 'pcfens/filebeat'

# Until my PRs to fix Issues #947 and #949 are merged.
#
mod 'elastic/elasticsearch',
  :git => 'https://github.com/alexharv074/puppet-elasticsearch.git',
  :ref => 'alex_master'

mod 'elastic/logstash'
mod 'arioch/redis'
mod 'elastic/kibana'
mod 'puppet/nginx'
mod 'camptocamp/archive'
mod 'thias/sysctl'

# Until next version is released.
#
mod 'basti1302/wait_for',
  :git => 'https://github.com/heini/puppet-wait-for',
  :ref => 'alexharvey/refreshonly_second_try'
