HOSTS:
  centos-72-x64:
    platform: el-7-x86_64
    box: puppetlabs/centos-7.2-64-nocm
    hypervisor: vagrant
    ip: 10.10.2.15
    vagrant_memsize: 8192
    volumes:
      sdb:
        size: 5000
      sdc:
        size: 20000
      sdd:
        size: 20000
    forwarded_ports:
      nginx:
        from: 10080
        to: 80
      kibana:
        from: 5601
        to: 5601
CONFIG:
  log_level: verbose
  type: foss
  masterless: true
