#cloud-config
---
package_update: true
packages:
  - curl
  - iptables-services
  - lvm2
  - tar
  - unzip

bootcmd:
  - [mkdir, -p, /etc/facter/facts.d]

write_files:
  - path: /etc/sysctl.d/99-elastic-lab.conf
    owner: root:root
    permissions: '0644'
    content: |
      vm.max_map_count = 262144
  - path: /etc/facter/facts.d/elk_lab.yaml
    owner: root:root
    permissions: '0644'
    content: |
      espv: /dev/disk/azure/scsi1/lun0
      elk_lab_source_cidr: __ELK_LAB_SOURCE_CIDR__

runcmd:
  - [udevadm, settle, --timeout=60]
  - [sysctl, --system]
  - [systemctl, enable, --now, iptables.service]
  - [systemctl, enable, --now, ip6tables.service]
